### ISSUE TITLE
a qusetion

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerAssignment#104]
hi. can i use a short genome region to extract signatures with this tool? just like 3kb.

**Comment by mdbarnesUCSD** [comment]
Hi, this is not recommended. Thanks!

**Comment by shenhaizhongdechanrao** [comment]
Thank you for your response. I understand that this cannot reflect the overall genomic signature. However, I hope to use this tool to discuss the mutation status of individual genes and reflect local features. Do you think this is feasible? If not, is it due to algorithmic limitations or biological significance?

**Comment by shenhaizhongdechanrao** [comment]
Thanks for your response. I understand that this cannot reflect the overall genomic signature. However, I hope to use this tool to discuss the mutation status of individual genes and reflect local features. Do you think this is feasible? If not, is it due to algorithmic limitations or biological significance?
yu


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlexandrovLab/SigProfilerAssignment"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月11日(星期六) 凌晨5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlexandrovLab/SigProfilerAssignment] a qusetion (Issue #104)





 
Hi, this is not recommended. Thanks!

**Comment by marcos-diazg** [comment]
Dear @shenhaizhongdechanrao,

Thanks for your question. Reporting local patterns of mutations for specific genes can definitely be meaningful. Indeed, this was one of the pioneer approaches used to understand the patterns of mutations in human cancer ([Olivier _et al._ 2010  Cold Spring Harb Perspect Biol](https://doi.org/10.1101/cshperspect.a001008)). However, it is important to point out that this was done only for the _TP53_ gene, as this is one of the most highly mutated genes in cancer, and a large number of _TP53_ mutated cases could be aggregated.

In any signature analysis, the number of samples and mutations is crucially important, as this will determine the power you have for identifying different signatures associated with specific patterns of mutations. This is the main reason why restricting the mutations in each sample to just a short genomic region is discouraged. By doing this, you will be limiting the number of mutations to very low values, and the algorithm will not be able to give you any helpful information.

My recommendation would be to aggregate your samples (generating one or several 'meta-samples') and perform a more qualitative analysis, similar to what was done in the _TP53_ analysis, instead of directly trying to extract mutational signatures. You can also perform an assignment analysis using these meta-samples, in order to identify the general patterns of mutations in your cohort. However, the caveat of this approach is that you will lose the sample-level resolution.

I hope this helps, and I'm happy to discuss further over email (mdiazgay@ucsd.edu).

Thanks for your interest! Best,

Marcos
