### ISSUE TITLE
Keyboard Interrupts Ignored

### ISSUE THREAD

**Issue by DarioS** [AlexandrovLab/SigProfilerAssignment#138]
Pressing Ctrl-C once realising incorrect file name is specified does nothing.

```
Assigning COSMIC sigs or Signature Database ...... 
1/15 [7%] in 0s (~0s, 18339.6/s) ^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

 It would be nice for SigProfilerAssignment to be responsive to user interrupts.

**Comment by rvangara** [comment]
Hi DarioS,

Thank you for bringing this issue to our attention.
The issue that SigProfilerAssignment does not currently handle keyboard interrupts (Ctrl-C) effectively during certain operations can happen due to the way Python handles blocking operations and signal processing as in performing blocking I/O operations (like reading large files or communicating with other workers and so on), it might not be checking for keyboard interrupts frequently.

We  will work on implementing a fix to ensure that the tool responds appropriately to user interrupts. In the meantime, you can try the following workaround to terminate the process:

You can use kill -9 <PID> by finding the process ID (PID) for now. 

These loops will get updated in the future versions of [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment).
