### ISSUE TITLE
median mutation burden per COSMIC signature

### ISSUE THREAD

**Issue by eltonjrv** [AlexandrovLab/SigProfilerAssignment#147]
Dear Marcus or anyone else from Alexandrov Lab,

I'd like to plot a mutation burden per COSMIC signature bubbleChart (like the one from Fig 3 - Alexandrov et al., 2020 - Nature).
I wonder if relying on values from the "Assignment_Solution/Activities/Assignment_Solution_Activities.txt" output file and dividing then by 2,800 (for the "per Mb" scale, since my samples are WGS), then doing median across samples with the signature, would be the right approach?
I went through the methods from that paper, but couldn't find what exact numeric input was provided for that chart.

Thanks very much in advance for your attention,
Best,
Elton

**Comment by marcos-diazg** [comment]
Thanks for your question, @eltonjrv! As mentioned on the COSMIC Mutational Signatures website, "the number of mutations per megabase was calculated by assuming that an average whole-exome has 30 Mb with sufficient coverage, whereas an average whole-genome has 2,800 Mb with sufficient coverage". This information is available on any signature-based website, under the "tissue distribution" section (e.g., https://cancer.sanger.ac.uk/signatures/sbs/sbs1/).

In addition, in order to replicate the figure you mentioned, it might be helpful for you to check the original code used to generate it at https://github.com/steverozen/Misc-PCAWG7-code.

I hope this helps, and please let us know if you have any further questions.

Marcos

**Comment by eltonjrv** [comment]
Thanks for your prompt reply, Marcos.
Yes indeed, I had already got the 2,800 Mb info from the COSMIC individual signatures websites. Thanks for reinforcing.
My main doubt was whether we can rely on the numerical values from the "Assignment_Solution/Activities/Assignment_Solution_Activities.txt" to be divided by 2,800, and then do median across samples with the signature.
I'll take a look later today on the steverozen codes for that figure, as you pointed.
Many thanks again.
Elton

**Comment by marcos-diazg** [comment]
Sure, you can take the results from the file you mentioned, as this corresponds to the activity matrix, indicating the total number of mutations assigned to each of the signatures in every sample. Regarding the median, if I'm not mistaken, in [Fig. 3 from Alexandrov et al. 2020](https://www.nature.com/articles/s41586-020-1943-3/figures/3), only the mutations per megabase of the samples containing the mutation were plotted, so you may need to remove the zeros before calculating the median. However, I encourage you to check the original code I shared earlier to accurately replicate it.

I hope this helps, and feel free to reach out over email if needed (mdiazgay@health.ucsd.edu).

Marcos

**Comment by eltonjrv** [comment]
Thanks for confirming, Marcos. That was really helpful!
Yeah, I'm pretty sure we need to remove all zeros to do the median (keeping only samples presenting the mutation, as Alexandrov 2020 says). 
I'm getting a similar "median mutation burden" range in my heatmap (individually for SBS, DBS, and ID) as the ones from Alexandrov 2020 Fig 3, respectively, which indicates I might be doing the right calculations. : )
Best,
Elton
