### ISSUE TITLE
Empty CNV_Decomposition_Plots.pdf 

### ISSUE THREAD

**Issue by aliahhawari** [AlexandrovLab/SigProfilerAssignment#58]
I've run the SigProfilerAssignment v0.0.18 and the CNV_Decomposition_Plots.pdf came up empty for all of the solutions.

**Comment by marcos-diazg** [comment]
Dear @aliahhawari,

Thanks for reaching out. Could you please provide more information about the commands you are using as well as your input data? I strongly suggest updating both SigProfilerAssignment and SigProfilerPlotting to their latest versions (v0.0.19 and v1.3.5, respectively).

**Comment by marcos-diazg** [comment]
Hi again Aliah,

That should be the expected behavior, but you can check anyway. Current versions are v1.3.6 for SigProfilerPlotting and v0.0.21 for SigProfilerAssignment.

If you want to use the reference COSMIC signatures, you don't need to provide anything on the `signature_database` parameter. COSMIC signatures v3.3 will be used as default.

Also, feel free to send us an example of your input data (my email is mdiazgay@health.ucsd.edu if you prefer), in case you are still experiencing any issues.

**Comment by rvangara** [comment]
Please reopen this ticket if issue persists,

Thanks
